<?php 
$servername = "demo.predictly.co"; 

$username = "demo"; 

$password = ""; 

$dbname = "imrb"; 

$con = mysql_connect($servername, $username, $password); 


if (!$con) {
  die('Could not connect: ' . mysql_error()); 

}
$centre= $_POST["centre"]?: '';
$age_group= $_POST["age_group"]?: '';
$panel= $_POST["panel"]?: '';
$age= $_POST["age"]?: '';
$vechile_name= $_POST["vechile_name"]?: '';
$intender= $_POST["intender"]?: '';
$rank_before= $_POST["rank_before"]?: '';
$concept= $_POST["concept"]?: '';
$price= $_POST["price"]?: '';
$mention= $_POST["mention"]?: '';

$vechile_code= $_POST["vehicle_code"]?: '';
$vechicle_before= $_POST["vechicle_before"]?: '';
$vechicle_after= $_POST["vechicle_after"]?: '';
$rank1= $_POST["rank1"]?: '';
$rank3= $_POST["rank3"]?: '';
$rank2= $_POST["rank2"]?: '';
$rank1_a= $_POST["rank1_a"]?: '';
$topic= $_POST["topic"]?: '';

 

mysql_select_db($dbname, $con); 

 $result = mysql_query("
SELECT CONCAT( 'name',',','parent',',','size',',','percentage',',','positive',',','negative')as 'name' 
union 
SELECT CONCAT( 'root',',',',',',') as name 
union
SELECT CONCAT( 'Head_Light',',','root',',',(select (count(case when aspects_disliked_problem like '%head%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape|glass|vision|design|size' then 1 end ) )from oct_16)) as name 
union
SELECT CONCAT( 'Shape',',','Head_Light',',',(select (count(case when aspects_disliked_problem like '%head%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Glass',',','Head_Light',',',(select (count(case when aspects_disliked_problem like '%head%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'glass|vision' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Design',',','Head_Light',',',(select (count(case when aspects_disliked_problem like '%head%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Head_Light',',',(select (count(case when aspects_disliked_problem like '%head%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Wheel',',','root',',',(select (count(case when aspects_disliked_problem like '%wheel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'grip|design|shape|size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Grip',',','Wheel',',',(select (count(case when aspects_disliked_problem like '%wheel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'grip' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Design',',','Wheel',',',(select (count(case when aspects_disliked_problem like '%wheel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Wheel',',',(select (count(case when aspects_disliked_problem like '%wheel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Wheel',',',(select (count(case when aspects_disliked_problem like '%wheel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Handle',',','root',',',(select (count(case when aspects_disliked_problem like '%handle%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'grip|size|comfort|style' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Grip',',','Handle',',',(select (count(case when aspects_disliked_problem like '%handle%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'grip' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Handle',',',(select (count(case when aspects_disliked_problem like '%handle%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Comfort',',','Handle',',',(select (count(case when aspects_disliked_problem like '%handle%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Stylish',',','Handle',',',(select (count(case when aspects_disliked_problem like '%handle%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'style' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Indicator',',','root',',',(select (count(case when aspects_disliked_problem like '%indicator%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape|design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Indicator',',',(select (count(case when aspects_disliked_problem like '%indicator%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Design',',','Indicator',',',(select (count(case when aspects_disliked_problem like '%indicator%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Seats',',','root',',',(select (count(case when aspects_disliked_problem like '%seat%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'length|wide' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Lengthy',',','Seats',',',(select (count(case when aspects_disliked_problem like '%seat%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'length|wide|comfort|outlool|look|shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Comfort',',','Seats',',',(select (count(case when aspects_disliked_problem like '%seat%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Outlook',',','Seats',',',(select (count(case when aspects_disliked_problem like '%seat%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'outlool|look' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Seats',',',(select (count(case when aspects_disliked_problem like '%seat%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Fuel_Tank',',','root',',',(select (count(case when aspects_disliked_problem like '%fuel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape|size|color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Fuel_Tank',',',(select (count(case when aspects_disliked_problem like '%fuel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Fuel_Tank',',',(select (count(case when aspects_disliked_problem like '%fuel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Color',',','Fuel_Tank',',',(select (count(case when aspects_disliked_problem like '%fuel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Tail_Lamp',',','root',',',(select (count(case when aspects_disliked_problem like '%tail_lamp%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'look|shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Looks',',','Tail_Lamp',',',(select (count(case when aspects_disliked_problem like '%tail_lamp%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'look' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Tail_Lamp',',',(select (count(case when aspects_disliked_problem like '%tail_lamp%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Guards',',','root',',',(select (count(case when aspects_disliked_problem like '%guard%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'safe|size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Safe',',','Guards',',',(select (count(case when aspects_disliked_problem like '%guard%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'safe' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Guards',',',(select (count(case when aspects_disliked_problem like '%guard%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Silencer',',','root',',',(select (count(case when aspects_disliked_problem like '%silencer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size|shine|cover' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Silencer',',',(select (count(case when aspects_disliked_problem like '%silencer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shine',',','Silencer',',',(select (count(case when aspects_disliked_problem like '%silencer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shine' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Cover',',','Silencer',',',(select (count(case when aspects_disliked_problem like '%silencer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'cover' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Graphics',',','root',',',(select (count(case when aspects_disliked_problem like '%graphics%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'sticker|shape|color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Sticker',',','Graphics',',',(select (count(case when aspects_disliked_problem like '%graphics%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'sticker' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Graphics',',',(select (count(case when aspects_disliked_problem like '%graphics%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Color',',','Graphics',',',(select (count(case when aspects_disliked_problem like '%graphics%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Colors',',','root',',',(select (count(case when aspects_disliked_problem like '%color%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'bright|dark' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Bright',',','Colors',',',(select (count(case when aspects_disliked_problem like '%color%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'bright' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Dark',',','Colors',',',(select (count(case when aspects_disliked_problem like '%color%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'dark' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Front_Dome',',','root',',',(select (count(case when aspects_disliked_problem like '%Front_Dome%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape|color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Front_Dome',',',(select (count(case when aspects_disliked_problem like '%Front_Dome%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Color',',','Front_Dome',',',(select (count(case when aspects_disliked_problem like '%Front_Dome%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Speedometer',',','root',',',(select (count(case when aspects_disliked_problem like '%speedometer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design|style|over_shape|mileage' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Design',',','Speedometer',',',(select (count(case when aspects_disliked_problem like '%speedometer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Stylish',',','Speedometer',',',(select (count(case when aspects_disliked_problem like '%speedometer%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'style' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Over_Shape',',','root',',',(select (count(case when aspects_disliked_problem like '%over_shape%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'over_shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Mileage',',','root',',',(select (count(case when aspects_disliked_problem like '%Mileage%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'mileage' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Power',',','root',',',(select (count(case when aspects_disliked_problem like '%power%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'easy|comfort|comfort|maintenance' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Easy',',','Power',',',(select (count(case when aspects_disliked_problem like '%power%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'easy' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Comfort',',','Power',',',(select (count(case when aspects_disliked_problem like '%power%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Comfort_',',','root',',',(select (count(case when aspects_disliked_problem like '%comfort%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Maintenance',',','root',',',(select (count(case when aspects_disliked_problem like '%maintenance%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'maintenance' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Safety',',','root',',',(select (count(case when aspects_disliked_problem like '%safety%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'safe|protect' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Safe',',','Safety',',',(select (count(case when aspects_disliked_problem like '%safety%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'safe' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Protect',',','Safety',',',(select (count(case when aspects_disliked_problem like '%safety%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'protect' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Carrier',',','root',',',(select (count(case when aspects_disliked_problem like '%Carrier%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'easy|shape|size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Easy',',','Carrier',',',(select (count(case when aspects_disliked_problem like '%Carrier%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'easy' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Carrier',',',(select (count(case when aspects_disliked_problem like '%Carrier%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Carrier',',',(select (count(case when aspects_disliked_problem like '%Carrier%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Side_Panel',',','root',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design|color|3d' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Design',',','Side_Panel',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'design' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Color',',','Side_Panel',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( '3D',',','Side_Panel',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP '3d' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Cover',',','root',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color|style|shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Color',',','Cover',',',(select (count(case when aspects_disliked_problem like '%Side_Panel%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'color' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Stylish',',','Cover',',',(select (count(case when aspects_disliked_problem like '%cover%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'style' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Cover',',',(select (count(case when aspects_disliked_problem like '%cover%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Foot_Rest',',','root',',',(select (count(case when aspects_disliked_problem like '%foot_rest%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort|wide' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Comfort',',','Foot_Rest',',',(select (count(case when aspects_disliked_problem like '%foot_rest%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'comfort' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Wide',',','Foot_Rest',',',(select (count(case when aspects_disliked_problem like '%foot_rest%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'wide' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Toolbox',',','root',',',(select (count(case when aspects_disliked_problem like '%tool%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size|shape' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Size',',','Toolbox',',',(select (count(case when aspects_disliked_problem like '%tool%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'size' then 1 end ) )from oct_16)) as name
union
SELECT CONCAT( 'Shape',',','Toolbox',',',(select (count(case when aspects_disliked_problem like '%tool%' and  centre like '%".$centre."%' and rank1  like '%".$rank1."%' and rank1_a  like '%".$rank1_a."%' and ( rank2  like '%".$rank2."%' and  rank3  like '%".$rank3."%' ) and age_group like '%".$age_group."%' and panel like '%".$panel."%' and age like '%".$age."%' and vechile_name like '%".$vechile_name."%' and intender like '%".$intender."%' and  vehicle_code like '%".$vechile_code."%' and mention like '%".$mention."%' and details_liked REGEXP 'shape' then 1 end ) )from oct_16)) as name

"); 
$rows = array(); 
while($r = mysql_fetch_array($result)) {
   echo $r[0]; 

   echo "\n"; 

   }



mysql_close($con); 

?>
 
